services:
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_PASSWORD=newpass  
      - POSTGRES_USER=myuser
    ports:
      - "5433:5432"            
    volumes:
      - lab3_data_final:/var/lib/postgresql/data 
      - ./sql_schema:/docker-entrypoint-initdb.d
volumes:
  lab3_data_final: